name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          sudo apt-get install pandoc
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install
      - name: Convert README.rst
        run: |
          cat << EOF > build_docs.sh
          #!/bin/bash
          poetry shell  # Activate the Poetry environment
          pandoc -f gfm -t rst --wrap=none  README.md -o doc/README.rst --filter doc/path_adjust_filter.py
          sphinx-apidoc -o doc ./
          sphinx-build doc _build -va
          EOF

          chmod +x build_docs.sh
          ./build_docs.sh    
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
          cname: cybench.agml.org
